# Generated by Django 5.1.7 on 2025-03-25 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_signup', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to='app_signup.usertype',
            ),
        ),
    ]
